apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: budget-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: auth
        static_configs:
          - targets: ["auth:80"]
      - job_name: budget
        static_configs:
          - targets: ["budget:80"]
