#!/usr/bin/env bash
# Generates k8s/secrets.yaml with real values for local kind deployment.
# Never commit the output file (already covered by .gitignore).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYS_DIR="$REPO_ROOT/services/auth/keys"
OUT_FILE="$REPO_ROOT/k8s/secrets.yaml"

if [ ! -f "$KEYS_DIR/private.pem" ] || [ ! -f "$KEYS_DIR/public.pem" ]; then
  echo "No JWT keypair found, generating one in $KEYS_DIR"
  mkdir -p "$KEYS_DIR"
  openssl genrsa -out "$KEYS_DIR/private.pem" 2048
  openssl rsa -in "$KEYS_DIR/private.pem" -pubout -out "$KEYS_DIR/public.pem"
fi

# hex, not base64: base64 can emit '/', '+', '=' which are not valid
# unencoded in a URL's userinfo section and will break DATABASE_URL parsing.
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 24)}"
DATABASE_URL="postgres://budget:${POSTGRES_PASSWORD}@postgres:5432/budgetapp"

{
  echo "# Generated by scripts/generate-secrets.sh -- DO NOT COMMIT."
  echo "apiVersion: v1"
  echo "kind: Secret"
  echo "metadata:"
  echo "  name: postgres-credentials"
  echo "  namespace: budget-app"
  echo "type: Opaque"
  echo "stringData:"
  echo "  POSTGRES_USER: budget"
  echo "  POSTGRES_PASSWORD: \"${POSTGRES_PASSWORD}\""
  echo "  POSTGRES_DB: budgetapp"
  echo "  database-url: \"${DATABASE_URL}\""
  echo "---"
  echo "apiVersion: v1"
  echo "kind: Secret"
  echo "metadata:"
  echo "  name: jwt-keys"
  echo "  namespace: budget-app"
  echo "type: Opaque"
  echo "stringData:"
  echo "  private.pem: |"
  sed 's/^/    /' "$KEYS_DIR/private.pem"
  echo "  public.pem: |"
  sed 's/^/    /' "$KEYS_DIR/public.pem"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
